[package]
name = "axum-oidc"
version = "0.1.0"
edition = "2024"

[dependencies]
axum-core = "0.5.2"
axum-extra = { version = "0.10.1", features = ["typed-header"] }
reqwest = "0.12.22"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.141"
